import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/components/layouts/Header';
import Footer from '@/components/layouts/Footer';
import ToGenerate from '@/components/layouts/ToGenerate';

import { NotificationListener } from '@/components/notification/NotificationListener';
import { ProviderWrapper } from '@/components/common/ProviderWrapper';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                {/* <Header></Header> */}

                {children}
                <ProviderWrapper>
                    <div className="absolute top-0 w-auto mx-auto">
                        <NotificationListener />
                    </div>
                </ProviderWrapper>

                <Footer></Footer>
                <ToGenerate></ToGenerate>
            </body>
        </html>
    );
}
